Refactor non-reactive behavior when checkbox changes
bezhanSalleh/filament-shield pull request #200
Opened 2023-06-26 22:25 UTC by a21ns1g4ts

Previously, unnecessary backend API calls were being made when toggling the check of the toggle button. This commit removes the redundant backend calls, resulting in improved performance and reduced server load. The toggle check now operates solely on the client-side, providing a smoother and more efficient user experience."

2023-06-26 22:29 UTC, a21ns1g4ts commented
#199 Improve performance

2023-07-21 21:40 UTC, faab007nl commented
When is this getting merged?

2023-08-01 15:02 UTC, Saifallak requested changes

2023-08-01 15:02 UTC, Saifallak commented on src/FilamentShield.php
> +    public static function geWidgetOptions()
```suggestion
    public static function getWidgetOptions()
```

2023-08-01 15:02 UTC, Saifallak commented on src/Resources/RoleResource.php
> +                                            ->afterStateHydrated(fn (Closure $set, Closure $get, $record) => static::setPermissionsStates(FilamentShield::geWidgetOptions(), $set, 'widgets', $record))
```suggestion
                                            ->afterStateHydrated(fn (Closure $set, Closure $get, $record) => static::setPermissionsStates(FilamentShield::getWidgetOptions(), $set, 'widgets', $record))
```

2023-08-01 15:02 UTC, Saifallak commented on src/Resources/RoleResource.php
> +                                            ->options(FilamentShield::geWidgetOptions()),
```suggestion
                                            ->options(FilamentShield::getWidgetOptions()),
```

2023-08-01 16:49 UTC, a21ns1g4ts commented
> When is this getting merged?

Due to time constraints and the need for a stable release, i will only be able to enable this pr after solve the select all cards front-end.

2023-09-16 16:11 UTC, closed without merging